applications:
  - kopete
mpd:
  host: localhost
  port: 6600
message:
  song:
#    format: ". .. ...zzzZ { ${artist} - ${title} } Zzzz... .. ."
    format: "rbMDNS RulZ! { ${artist} - ${title} } [http://yitsushi.github.com/rbMDNS/]"
    status: "Busy"
  state:
    stop:
      text:   "I use rbMDNS [http://yitsushi.github.com/rbMDNS/]! Status of my MPD: Stopped"
      status: "Away"
