applications:
  - kopete
mpd:
  host: localhost
  port: 6600
message:
  song:
    format: ". .. ...zzzZ { ${artist} - ${album} } Zzzz... .. ."
    status: "Busy"
  stat:
    stop:
      text:   "I use rbMDNS [http://yitsushi.github.com/rbMDNS/]! Status of my MPD: Stopped"
      status: "Away"
